### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by Sycamoretree** [pokemon-mini/minlibtowav#1]
Hello! When ran these codes I finding a wrong writing in your code which located in the 129th line，maybe you can check it!

**Comment by Jhynjhiruu** [comment]
It works fine for me. Are you sure you have the latest Python version and you correctly extracted the data?

**Comment by Sycamoretree** [comment]
> 
> 
> It works fine for me. Are you sure you have the latest Python version and you correctly extracted the data?

yeah,I used your code to transfer wav  to midi data with  latest Python version and there is something wrong.
![图片](https://user-images.githubusercontent.com/37615133/76625789-f2a81400-6572-11ea-869c-8c9093dffb54.png)
maybe you can dele ":"

**Comment by Sycamoretree** [comment]
thanks , I checked it again,you are right .‘:=’ is a new grama.thank u again.

**Comment by Sycamoretree** [comment]
I am trying to convert a wav file to midi file,but I find the result is not good，i find this by comparing  spectrums of original wav file and transfered file.
I want to know if you code can transfer wav to midi rightly.
if you kown this,could u please help me ,thanks

**Comment by Jhynjhiruu** [comment]
My code cannot convert WAV to MIDI, it can only convert Minlib's music format to MIDI or WAV.

**Comment by Sycamoretree** [comment]
I get it ,thanks
